# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-VhaRdhVRmMievSgb2Ib9d4NG3tOe00_
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/drive/MyDrive/NETflix Data/Copy of combined_data_1.txt.zip',header= None,names=['cus_ID','ratings'],usecols=[0,1])

df

df.isnull().sum()

movie_count =df.isnull().sum()['ratings']
movie_count

total_uni = df['cus_ID'].nunique()
total_uni

cust_count = total_uni-movie_count
cust_count

ratings_count = df['ratings'].count()-movie_count
ratings_count

stars_count = df['ratings'].value_counts()
stars_count

movie_id = None
movie_list = []

for customer in df['cus_ID']:
  if ":" in customer:
    movie_id = int(customer.replace(":",""))
  movie_list.append(movie_id)

movie_list

df['movie_ID']= movie_list
df

df.dropna(inplace=True)

df

df.info()

df['cus_ID']=df['cus_ID'].astype('int')
df['ratings']=df['ratings'].astype('int')
df['movie_ID']=df['movie_ID'].astype('int')

df.info()

movie_rat_count=df['movie_ID'].value_counts()
movie_rat_count

bench_mark1 =round(movie_rat_count.quantile(0.6),0)
bench_mark1

drop_movie=movie_rat_count[movie_rat_count<bench_mark1].index
drop_movie

cust_rat_count=df['cus_ID'].value_counts()
cust_rat_count

bench_mark2=round(cust_rat_count.quantile(0.6),0)
bench_mark2

cust_rat_index=cust_rat_count[cust_rat_count<bench_mark2].index
cust_rat_index

movie_rat_count,cust_rat_count

df=df[~df['movie_ID'].isin(drop_movie)]
df=df[~df['cus_ID'].isin(cust_rat_index)]

df

df

movie_title = pd.read_csv('/content/Copy-of-movie_titles-2.zip',encoding='ISO-8859-1',header=None,names=['Movie_ID','Year','Name'],usecols=[0,1,2])

movie_title

!pip install scikit-surprise

from surprise import Dataset,Reader,SVD
from surprise.model_selection import cross_validate

reader = Reader()

data = Dataset.load_from_df(df[['cus_ID','ratings','movie_ID']][:100000],reader)

data

model=SVD()

user_1331154=df[df['cus_ID']==1331154]

cross_validate(model,data,measures=['RMSE'],cv=3)

dummy_title=movie_title.copy()

drop_movie_index=drop_movie

dummy_title=dummy_title[~dummy_title['Movie_ID'].isin(drop_movie_index)]
dummy_title

est_pred=[]
for Movie in dummy_title['Movie_ID']:
  rating=model.predict(1331154,Movie).est
  est_pred.append(rating)


dummy_title['rating']=est_pred
dummy_title

dummy_title.sort_values('rating',ascending=False).head()

